SPACESHIP_PROMPT_ORDER=(
  user
  host
  dir
  git
  line_sep
  char
)
SPACESHIP_RPROMPT_ORDER=(exec_time exit_code)

SPACESHIP_PROMPT_ASYNC=false
SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_SEPARATE_LINE=true

SPACESHIP_USER_SHOW=always
SPACESHIP_USER_PREFIX=""
SPACESHIP_USER_SUFFIX="@"
SPACESHIP_USER_COLOR=green

SPACESHIP_HOST_SHOW=always
SPACESHIP_HOST_PREFIX=""
SPACESHIP_HOST_SUFFIX=" "
SPACESHIP_HOST_COLOR=green

SPACESHIP_DIR_PREFIX=""
SPACESHIP_DIR_SUFFIX=" "
SPACESHIP_DIR_TRUNC=3
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_DIR_COLOR=cyan

SPACESHIP_GIT_PREFIX=""
SPACESHIP_GIT_SUFFIX=" "
SPACESHIP_GIT_BRANCH_PREFIX="on "
SPACESHIP_GIT_BRANCH_COLOR=magenta

SPACESHIP_EXEC_TIME_PREFIX=""
SPACESHIP_EXEC_TIME_SUFFIX=""
SPACESHIP_EXEC_TIME_COLOR=yellow
SPACESHIP_EXEC_TIME_ELAPSED=1
SPACESHIP_EXEC_TIME_PRECISION=1

SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_PREFIX=""
SPACESHIP_EXIT_CODE_SUFFIX=""
SPACESHIP_EXIT_CODE_SYMBOL="exit "

SPACESHIP_CHAR_SYMBOL="↪ "
SPACESHIP_CHAR_SYMBOL_SUCCESS="↪ "
SPACESHIP_CHAR_SYMBOL_FAILURE="↪ "
SPACESHIP_CHAR_COLOR_SUCCESS=green
SPACESHIP_CHAR_COLOR_FAILURE=red
