import { formatHelp } from "../src/cli/index.ts";

interface ArgumentDescription {
  name: string;
  type: string;
  description?: string;
  required?: boolean;
  aliases?: string[];
  options?: string[];
}

interface CommandDescription {
  name: string;
  description?: string;
  arguments?: ArgumentDescription[];
  subcommands?: CommandDescription[];
}

interface RootDescription {
  name: string;
  description?: string;
  options?: ArgumentDescription[];
  commands?: CommandDescription[];
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function optionLabel(argument: ArgumentDescription): string {
  const long = `--${argument.name}`;
  const aliases = argument.aliases?.map((alias) => `-${alias}`) ?? [];
  const value = argument.type === "boolean" ? "" : " <value>";
  return [...aliases, `${long}${value}`].map((part) => `\`${part}\``).join(", ");
}

function usageToken(argument: ArgumentDescription): string {
  if (argument.type === "positional") {
    return argument.required ? `<${argument.name}>` : `[${argument.name}]`;
  }

  const value = argument.type === "boolean" ? "" : " <value>";
  const token = `--${argument.name}${value}`;
  return argument.required ? token : `[${token}]`;
}

function renderArguments(arguments_: ArgumentDescription[]): string[] {
  const lines = ["| Argument | Type | Description |", "| --- | --- | --- |"];

  for (const argument of arguments_) {
    const label = argument.type === "positional" ? `\`${argument.name}\`` : optionLabel(argument);
    const choices = argument.options?.length
      ? ` Choices: ${argument.options.map((value) => `\`${value}\``).join(", ")}.`
      : "";
    const required = argument.required ? " Required." : "";
    lines.push(
      `| ${label} | ${escapeCell(argument.type)} | ${escapeCell(argument.description ?? "")}${choices}${required} |`,
    );
  }

  return lines;
}

function renderCommand(command: CommandDescription, parents: string[]): string[] {
  const path = [...parents, command.name];
  const arguments_ = command.arguments ?? [];
  const subcommands = command.subcommands ?? [];
  const usage = [
    path.join(" "),
    ...arguments_.map(usageToken),
    subcommands.length ? "<command>" : "",
  ]
    .filter(Boolean)
    .join(" ");
  const lines = [
    `## \`${path.join(" ")}\``,
    "",
    command.description ?? "",
    "",
    `**Usage:** \`${usage}\``,
    "",
  ];

  if (arguments_.length) {
    lines.push(...renderArguments(arguments_), "");
  }

  if (subcommands.length) {
    lines.push("| Subcommand | Description |", "| --- | --- |");
    for (const subcommand of subcommands) {
      lines.push(
        `| \`${[...path, subcommand.name].join(" ")}\` | ${escapeCell(subcommand.description ?? "")} |`,
      );
    }
    lines.push("");
  }

  for (const subcommand of subcommands) {
    lines.push(...renderCommand(subcommand, path));
  }

  return lines;
}

const root = JSON.parse(await formatHelp(true)) as RootDescription;
const commands = root.commands ?? [];
const rootCommand: CommandDescription = {
  name: root.name,
  description: root.description,
  arguments: root.options,
  subcommands: commands,
};
const output = [
  "<!-- Generated by `mise run docs:commands`. Do not edit manually. -->",
  "",
  "# CLI command reference",
  "",
  "Complete command, argument, option, and subcommand reference generated from the CLI definitions.",
  "",
  ...renderCommand(rootCommand, []),
].join("\n");

await Bun.write(new URL("../docs/commands.md", import.meta.url), `${output.trimEnd()}\n`);
